services:
  db:
    container_name: mysql-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: master
      MYSQL_DATABASE: employee
    networks:
      - net-emp
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    container_name: backend
    build:
      context: ./emp_backend
    networks:
      - net-emp
    ports:
      - 8080:8080
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./employee_frontend
    ports:
      - 4200:80

networks:
  net-emp: {}

volumes:
  mysql-data:
    # external: true
    # name: mysql-data
